name: Test environments

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa-test
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.0

    - name: Build
      run: |
        node test param1 ${{ vars.CUSTOM_PATH }} param3 param4-${{ vars.CUSTOM_PATH }}-1111
        echo ${{ vars.CUSTOM_PATH }}
        npm install
        npx webpack
