name: Test environments

on:
  workflow_dispatch:
    inputs:
        bottler:
          description: 'Bottler id'
          required: true
          default: ''
jobs:
  build-dev:
    name: 'BUILD DEV'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: qa-test
    env:
      CUSTOM_PATH1: ${{ vars.CUSTOM_PATH }}
      IN_BOTTLER: ${{ github.event.inputs.bottler }}

    steps:
    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CID }}
        tenant-id: ${{ secrets.TID }}
        subscription-id: ${{ secrets.SS }}
    #- name: Az CLI login
    #  uses: azure/login@v1
    #  with:
    #    client-id: ${{ secrets.CID }}
    #    tenant-id: ${{ secrets.TID }}
    #    subscription-id: ${{ secrets.SS }}
    - name: Build
      run: |
        echo ${{ github.event.inputs.bottler }}
        #node test param1 ${{ vars.CUSTOM_PATH }} param3 param4-${{ vars.CUSTOM_PATH }}-1111
        echo ${{ env.CUSTOM_PATH1 }}
        echo ${{ env.IN_BOTTLER }}
        #npm install
        #npx webpack
        
  build-qa:
    name: 'BUILD QA'
    needs: build-dev
    runs-on: ubuntu-latest
    environment: prod-test
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.0

    - name: Build
      run: |
        echo ${{ github.event.inputs.bottler }}
        #node test param1 ${{ vars.CUSTOM_PATH }} param3 param4-${{ vars.CUSTOM_PATH }}-1111
        echo ${{ vars.CUSTOM_PATH }}
        #npm install
        #npx webpack
