name: NodeJS with Webpack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa-test
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.0

    - name: Build
      run: |
        echo ${{ vars.CUSTOM_PATH }}
        npm install
        npx webpack
