/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/race-car/model.gltf'
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_body014.geometry} material={materials.paintRed} />
      <mesh geometry={nodes.Mesh_body014_1.geometry} material={materials.plastic} />
      <mesh geometry={nodes.Mesh_body014_2.geometry} material={materials.window} />
      <mesh geometry={nodes.Mesh_body014_3.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft028.geometry} material={nodes.Mesh_wheel_frontLeft028.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft028_1.geometry} material={nodes.Mesh_wheel_frontLeft028_1.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft028_2.geometry} material={nodes.Mesh_wheel_frontLeft028_2.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft029.geometry} material={nodes.Mesh_wheel_frontLeft029.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft029_1.geometry} material={nodes.Mesh_wheel_frontLeft029_1.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft029_2.geometry} material={nodes.Mesh_wheel_frontLeft029_2.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft030.geometry} material={nodes.Mesh_wheel_frontLeft030.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft030_1.geometry} material={nodes.Mesh_wheel_frontLeft030_1.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft030_2.geometry} material={nodes.Mesh_wheel_frontLeft030_2.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft011.geometry} material={nodes.Mesh_wheel_frontLeft011.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft011_1.geometry} material={nodes.Mesh_wheel_frontLeft011_1.material} />
      <mesh geometry={nodes.Mesh_wheel_frontLeft011_2.geometry} material={nodes.Mesh_wheel_frontLeft011_2.material} />
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/race-car/model.gltf')
